baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5
buildDrafts = false

[params]
  contentTypeName = "posts"
  categories = ["weekly"]
  themeColor = "orange"
  showMenuItems = 2
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  autoCover = true
  # favicon = "favicon.ico"
  oneHeadingSize = false

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "Alvan's Blog"
    subtitle = "Blogs and notes I take while learning & discovering new stuff"
    owner = "Alvan Rahimli"
    keywords = "tech blog alvan alvanrahimli rahimli dotnet developer c# razor pages golang go"
    copyright = "Alvan Rahimli"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Alvan's Blog"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About me"
        url = "/posts/about-me"
      [[languages.en.menu.main]]
        identifier = "cv"
        name = "Look at my CV"
        url = "https://cv.rahim.li/"
      [[languages.en.menu.main]]
        identifier = "weekly-posts"
        name = "Weekly rants"
        url = "/tags/weekly"
