baseurl = "https://rahim.li/"
languageCode = "en-us"
theme = "mainroad"
paginate = 8
buildDrafts = false

[Params.logo]
	image = false
	title = "Alvan's blog"
	subtitle = "Blogs and notes I take while learning & discovering new stuff"

[Params.thumbnail]
	visibility = ["list", "post"]
	
[Params.widgets.social]
	# Enable parts of social widget
	facebook = "alvanrahimli"
	twitter = "alvan_rahim"
	linkedin = "alvan-rahimli"
	github = "alvanrahimli"
	email = "alvan@rahim.li"

[Params.widgets]
	recent_num = 10
[Params]
	googleFontsLink = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Alvan's Blog"
    subtitle = "Blogs and notes I take while learning & discovering new stuff"
    owner = "Alvan Rahimli"
    keywords = "tech blog alvan alvanrahimli rahimli dotnet developer c# razor pages golang go"
    copyright = "Alvan Rahimli"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Alvan's Blog"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About me"
        url = "/posts/about-me"
	  [[languages.en.menu.main]]
	  	identifier = "home"
		name = "Home page"
		url = "/"
	  [[languages.en.menu.main]]
        identifier = "cv"
        name = "Look at my CV"
        url = "https://cv.rahim.li/"
      [[languages.en.menu.main]]
        identifier = "weekly-posts"
        name = "Weekly rants"
        url = "/tags/weekly"
