# Base URL used when generating links to your pages
# Set to the URL for your site
baseURL = "https://rahim.li"

# The name of this wonderful theme ;-).
theme = 'hugo-bearblog'

# Basic metadata configuration for your blog.
title = "Alvan's digital garden"
author = "Alvan Rahimli"
copyright = "Licensed under CC-BY-4.0 · Alvan Rahimli"
languageCode = "en-US"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  description = "Alvan's digital garden. Posts, notes and essays I write while learning & discovering stuff"

  favicon = "images/favicon.png"

  # For twitter etc. preview
  # images = ["images/share.png"]

  title = "Alvan's blog : Learning & discovering new stuff"

  hideMadeWithLine = true

  # Default: "02 Jan, 2006"
  # dateFormat = "2006-01-02"
